version: '3'

services:
  nats:
    image: nats
    ports:
      - "8222:8222"
      - "4222:4222"
  web:
    build:
        context: ./services/web/
        dockerfile: ./config/docker/Dockerfile
    ports:
        - "3000:3000"
  backend:
    build:
        context: ./services/backend/
        dockerfile: ./config/docker/Dockerfile
    ports:
        - "4000:4000"