version: '3'

services:
  web:
    build:
        context: ./services/web/
        dockerfile: ./config/docker/Dockerfile
    ports:
        - "7000:3000"
  backend:
    build:
        context: ./services/backend/
        dockerfile: ./config/docker/Dockerfile
    ports:
        - "7100:4000"
    depends_on: 
      - mongo
      - nats
  nats:
    image: nats
    ports:
      - "7200:8222"
  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - ./data/db:/data/db