version: '3'

services:
  web:
    build:
        context: ./services/web/
        dockerfile: ./config/docker/Dockerfile
    ports:
        - "3000:3000"
  backend:
    build:
        context: ./services/backend/
        dockerfile: ./config/docker/Dockerfile
    ports:
        - "4000:4000"