version: '3'

services:
  web:
    build:
        context: ./services/web/
        dockerfile: ./config/docker/Dockerfile
    ports:
        - "7000:3000"
  backend:
    build:
        context: ./services/backend/
        dockerfile: ./config/docker/Dockerfile
    ports:
        - "7100:4000"
  nats:
    image: nats
    ports:
      - "7200:8222"
  database:
    image: mongo
    environment: 
      - MONGO_INITDB_DATABASE=game-database
    ports:
      - '27017-27019:27017-27019'